### ISSUE TITLE
Error in running the code via 

### ISSUE THREAD

**Issue by elagrija** [Karkas66/CelestialSpark#2]
![image](https://github.com/Karkas66/CelestialSpark/assets/13571168/8dd9a636-6321-46c7-aae2-dd8904188264)

**Comment by elagrija** [comment]
May i get your suggestions to resolve this

**Comment by Karkas66** [comment]
i recommend using a default Kali System for compiling or try to install mingw-w64, nasm and pyton3-pefile from your Linux vendor repositories.  It compiles without issues on my Kali and latest Ubuntu System

**Comment by elagrija** [comment]
Thank you
