### ISSUE TITLE
Problem with Meterpreter reverse tcp

### ISSUE THREAD

**Issue by elagrija** [Karkas66/CelestialSpark#3]
![issue](https://github.com/Karkas66/CelestialSpark/assets/13571168/d30bd12e-afdc-4a2d-acd1-877fd96233aa)

**Comment by elagrija** [comment]
Request your time to look at this and help us.

**Comment by Karkas66** [comment]
U used the 32 bit meterpreter
set PAYLOAD windows/x64/meterpreter/reverse_tcp
would be correct since Stardust only supports 64 Bit architecture

**Comment by elagrija** [comment]
Thank you So much.. Got the desired output

**Comment by elagrija** [comment]
![issue in production](https://github.com/Karkas66/CelestialSpark/assets/13571168/71f12b0f-98dd-4e8b-8cb7-78a6f3e334cd)

**Comment by elagrija** [comment]
Hello, tried to run in the presence of EDR. However got this message from running dll... Is this because of EDR

**Comment by Karkas66** [comment]
This problem is not related to CelestialSpark, use another loader, for Example https://github.com/reveng007/DarkWidow
There is a V2 in the repo, it works very well

**Comment by elagrija** [comment]
Ok. Will close the issue.

**Comment by elagrija** [comment]
Thanks for your time and Suggestions.
